cproject/capp/urls.py
from django.urls import path
from . import views
app_name='shop'
urlpatterns = [

    path('',views.home,name='home'),
    path('ComputerScience',views.cs,name='ComputerScience'),
    path('BioMaths',views.bio,name='BioMaths'),
    path('Commerce',views.com,name='Commerce'),
    path('Humanities',views.hum,name='Humanities'),
    path('PhysicalEducation',views.pe,name='PhysicalEducation'),


]

cproject/cproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('capp.urls')),
    path('credentials', include('credentials.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

cproject/credentials/urls.py
from django.urls import path
from . import views
app_name='credentials'
urlpatterns = [


    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('logout',views.logout,name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('order', views.order, name='order'),
    path('success', views.success, name='success'),
]

cproject/capp/models.py
from django.db import models

# Create your models here.
class Department(models.Model):
    d_name = models.CharField(max_length=50)

    def __str__(self):
        return self.d_name


class Course(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    c_name = models.CharField(max_length=50)

    def __str__(self):
        return self.c_name

class Material(models.Model):
    m_name = models.CharField(max_length=50)

    def __str__(self):
        return self.m_name

class Student(models.Model):
    name = models.CharField(max_length=100)
    dob = models.DateField()
    age = models.IntegerField()
    gender = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=15)
    mail_id = models.EmailField()
    address = models.TextField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    purpose = models.CharField(max_length=50)
    materials_provide = models.ManyToManyField(Material)

    def __str__(self):
        return self.name

cproject/credentials/models.py
from django.db import models

# Create your models here.

cproject/capp/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'index.html')

def cs(request):
    return render(request,'cs.html')

def bio(request):
    return render(request,'biology.html')

def com(request):
    return render(request,'commerce.html')

def hum(request):
    return render(request,'humanities.html')

def pe(request):
    return render(request,'pe.html')

cproject/credentials/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib import messages

# Create your views here.
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from capp.models import Student, Department, Course, Material


# Create your views here.
def register(request):
    if request.method=='POST':
        username=request.POST['username']
        pass1=request.POST['pass1']
        pass2=request.POST['pass2']
        if pass1==pass2:
            if User.objects.filter(username=username).exists():
                messages.info(request,'Username Taken')
                return redirect('credentials:register')

            else:
                user=User.objects.create_user(username=username,password=pass1)
                user.save()
                return redirect('credentials:login')
            print('user created')

        else:
            messages.info(request,'password not matched')
            return redirect('credentials:register')
        return redirect('/')
    return render(request,'register.html')

def login(request):
    if request.method=='POST':
        username=request.POST['username']
        passw=request.POST['pass']
        user=auth.authenticate(username=username,password=passw)

        if user is not None:
            auth.login(request,user)
            return redirect('credentials:dashboard')
        else:
            messages.info(request,'Invalid Credentials')
            return redirect('credentials:login')

    return render(request,'login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

def dashboard(request):
    return render(request,'dashboard.html')


def order(request):
    if request.method == 'POST':
        # Get data from the POST request
        name = request.POST.get('name')
        dob = request.POST.get('dob')
        age = request.POST.get('age')
        gender = request.POST.get('gender')
        phone_number = request.POST.get('phone_number')
        mail_id = request.POST.get('mail_id')
        address = request.POST.get('address')
        department_id = request.POST.get('department')
        course_id = request.POST.get('course')
        purpose = request.POST.get('purpose')
        materials_provide = request.POST.getlist('materials_provide')

        # Create a new Student instance and save it to the database
        student = Student.objects.create(
            name=name,
            dob=dob,
            age=age,
            gender=gender,
            phone_number=phone_number,
            mail_id=mail_id,
            address=address,
            department_id=department_id,
            course_id=course_id,
            purpose=purpose,


        )

        # Add materials provided by the student
        student.materials_provide.set(materials_provide)

        messages.success(request, 'Form submitted successfully!')
        return redirect('credentials:success')

    # Get the list of departments, courses, and materials to pass to the template
    departments = Department.objects.all()
    courses = Course.objects.all()
    materials = Material.objects.all()

    return render(request, 'order.html', {'departments': departments, 'courses': courses, 'materials': materials})

def success(request):
    return render(request,'orderconfirm.html')

cproject/templates/biology.html
{% extends 'base.html' %}

{% load static %}

{% block header_image %}
    <header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background-image:url('{% static 'images/bio.jpg' %}');">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <div class="display-t">
                        <div class="display-tc animate-box" data-animate-effect="fadeIn">

                                <h1>Bio Mathematics</h1>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}


{% block content %}
  <h1>Bio Maths</h1>
<p>Bio-Mathematics Department: Where Biology Meets Mathematics. Dive into the fascinating intersection of life sciences and mathematical principles. Our Bio-Mathematics department explores the intricate patterns of life, employing mathematical models to unravel the mysteries of biological systems. </p>
<p>	Join us in cultivating a deep understanding of both the living world and the quantitative tools that reveal its secrets.</p>

{% endblock %}

cproject/templates/dashboard.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Shop</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by gettemplates.co" />




  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	 <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
	 <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i" rel="stylesheet">

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-Wk/1BI8Rm5NZqHbfPeP8qVaaE/M+J+muUnvFuXi6ZRJ1dSfMdgwAT3A9z1WzLWK4q4lvHbgUVF9Y4ciH3zyFydA==" crossorigin="anonymous" />
<style>
	/* Style for the red dot */
.user-list-item {
  position: relative;
}

.user-list-item::before {
  content: "";
  position: absolute;
  top: 35%;
  right: 10px; /* Adjust the distance from the right edge */
  width: 10px;
  height: 10px;
  background-color: red;
  border-radius: 50%;
  display: block;
}

	</style>
	</head>
	<body>



	<div id="page">
	<nav class="fh5co-nav" role="navigation">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-xs-2">
					<div id="fh5co-logo"><a>Academic Aisle</a></div>
				</div>
				<div class="col-md-6 col-xs-6 text-center menu-1">
					<ul>
						{% if user.is_authenticated %}
						<li><span class="user-list-item"></span><a>{{ user.username }}</a></li>
									<li><a href="{% url 'credentials:logout' %}">Logout</a></li>
									<li><a href="{% url 'credentials:order' %}">Order Here</a></li>
							{% else %}
						<li><a href="{% url 'credentials:login' %}">Login</a></li>
						<li><a href="{% url 'credentials:register' %}">Register</a></li>
						{% endif %}


						<li class="has-dropdown">
							<a>Department</a>
							<ul class="dropdown">
								<li><a href="{% url 'shop:ComputerScience' %}">Computer Science</a></li>
								<li><a href="{% url 'shop:BioMaths' %}">Bio Maths</a></li>
								<li><a href="{% url 'shop:Commerce' %}">Commerce</a></li>
								<li><a href="{% url 'shop:Humanities' %}">Humanities</a></li>
								<li><a href="{% url 'shop:PhysicalEducation' %}">Physical Education</a></li>
							</ul>
						</li>
					</ul>
				</div>

			</div>

		</div>
	</nav>

	<aside id="fh5co-hero" class="js-fullheight">
		<div class="flexslider js-fullheight">
			<ul class="slides">
			<li style="background-image: url('{% static 'images/inbg.jpg' %}');">

		   		<div class="overlay-gradient"></div>
		   		<div class="container">
		   			<div class="col-md-6 col-md-offset-3 col-md-pull-3 js-fullheight slider-text">
		   				<div class="slider-text-inner">
		   					<div class="desc">

		   						<h2>Academic Aisle</h2>
		   						<p>Welcome to Academic Aisle, where learning meets style. Explore a curated selection of educational essentials, from science to literature, designed to enhance the student experience. Discover quality products that inspire knowledge and creativity. Elevate your educational journey with our thoughtfully chosen school supplies. Shop smart, learn brilliantly!</p>
		   					</div>
		   				</div>
		   			</div>
		   		</div>
		   	</li>



		  	</ul>
	  	</div>
	</aside>



	<div id="fh5co-product">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<span>Cool Stuff</span>
					<h2>Products.</h2>
					<p>Uncover a world of academic excellence with our carefully curated product selection. </p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 text-center animate-box">
					<div class="product">
						<div class="product-grid" style="background-image:url('{% static 'images/note.jpg' %}');">
							<div class="inner">
								<p>
									<a href="single.html" class="icon"><i class="icon-eye"></i></a>
								</p>
							</div>
						</div>
						<div class="desc">
							<h3><a href="single.html">Notebooks</a></h3>
							<span class="price">Rs.350</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="product">
						<div class="product-grid" style="background-image:url('{% static 'images/pen.jpg' %}');">
							<span class="sale">Sale</span>
							<div class="inner">
								<p>
									<a href="single.html" class="icon"><i class="icon-eye"></i></a>
								</p>
							</div>
						</div>
						<div class="desc">
							<h3><a href="single.html">Pen</a></h3>
							<span class="price">Rs.100</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="product">
						<div class="product-grid" style="background-image:url('{% static 'images/pencil.jpg' %}');">
							<div class="inner">
								<p>
									<a href="single.html" class="icon"><i class="icon-eye"></i></a>
								</p>
							</div>
						</div>
						<div class="desc">
							<h3><a href="single.html">Pencil</a></h3>
							<span class="price">Rs.80</span>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 text-center animate-box">
					<div class="product">
						<div class="product-grid" style="background-image:url('{% static 'images/cal1.jpg' %}');">
							<div class="inner">
								<p>
									<a href="single.html" class="icon"><i class="icon-eye"></i></a>
								</p>
							</div>
						</div>
						<div class="desc">
							<h3><a href="single.html">Scientific Calculator</a></h3>
							<span class="price">Rs.1800</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="product">
						<div class="product-grid" style="background-image:url('{% static 'images/pe.jpg' %}');">
							<div class="inner">
								<p>
									<a href="single.html" class="icon"><i class="icon-eye"></i></a>
								</p>
							</div>
						</div>
						<div class="desc">
							<h3><a href="single.html">Physical Education Kit</a></h3>
							<span class="price">Rs.1000</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center animate-box">
					<div class="product">
						<div class="product-grid" style="background-image:url('{% static 'images/hand.jpg' %}');">
							<div class="inner">
								<p>

									<a href="single.html" class="icon"><i class="icon-eye"></i></a>
								</p>
							</div>
						</div>
						<div class="desc">
							<h3><a href="single.html">Hand Sanitizer</a></h3>
							<span class="price">Rs.160</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>



	<div id="fh5co-counter" class="fh5co-bg fh5co-counter" style="background-image:url(images/img_bg_5.jpg);">
		<div class="container">
			<div class="row">
				<div class="display-t">
					<div class="display-tc">
						<div class="col-md-3 col-sm-6 animate-box">
							<div class="feature-center">
								<span class="icon">
									<i class="icon-eye"></i>
								</span>

								<span class="counter js-counter" data-from="0" data-to="100" data-speed="5000" data-refresh-interval="50">1</span>
								<span class="counter-label">Quality</span>

							</div>
						</div>
						<div class="col-md-3 col-sm-6 animate-box">
							<div class="feature-center">
								<span class="icon">
									<i class="icon-shopping-cart"></i>
								</span>

								<span class="counter js-counter" data-from="0" data-to="100" data-speed="5000" data-refresh-interval="50">1</span>
								<span class="counter-label">Satisfaction</span>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 animate-box">
							<div class="feature-center">
								<span class="icon">
									<i class="icon-shop"></i>
								</span>
								<span class="counter js-counter" data-from="0" data-to="700" data-speed="5000" data-refresh-interval="50">1</span>
								<span class="counter-label">All Products</span>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 animate-box">
							<div class="feature-center">
								<span class="icon">
									<i class="icon-clock"></i>
								</span>

								<span class="counter js-counter" data-from="0" data-to="5605" data-speed="5000" data-refresh-interval="50">1</span>
								<span class="counter-label">Hours Spent</span>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


	<footer id="fh5co-footer" role="contentinfo">
		<div class="container">


			<div class="row copyright">
				<div class="col-md-12 text-center">
					<p>
						<small class="block">&copy; 2023 Academic Aisle. All Rights Reserved.</small>
						<small class="block">Designed by <a href="http://freehtml5.co/" target="_blank">Malavika.A</a> </small>
					</p>

				</div>
			</div>

		</div>
	</footer>
	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>

	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Carousel -->
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<!-- countTo -->
	<script src="{% static 'js/jquery.countTo.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

cproject/templates/order.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Shop</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by gettemplates.co" />




  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	 <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
	 <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i" rel="stylesheet">

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-Wk/1BI8Rm5NZqHbfPeP8qVaaE/M+J+muUnvFuXi6ZRJ1dSfMdgwAT3A9z1WzLWK4q4lvHbgUVF9Y4ciH3zyFydA==" crossorigin="anonymous" />
<style>
	/* Style for the red dot */
.user-list-item {
  position: relative;
}

.user-list-item::before {
  content: "";
  position: absolute;
  top: 35%;
  right: 10px; /* Adjust the distance from the right edge */
  width: 10px;
  height: 10px;
  background-color: red;
  border-radius: 50%;
  display: block;
}

	</style>
	</head>
	<body style="background-image: url('{% static 'images/bgg1.jpg' %}'); background-size: cover;">




	<div id="page">
	<nav class="fh5co-nav" role="navigation">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-xs-2">
					<div id="fh5co-logo"><a>Academic Aisle</a></div>
				</div>
				<div class="col-md-6 col-xs-6 text-center menu-1">
					<ul>
						{% if user.is_authenticated %}
						<li><span class="user-list-item"></span><a>{{ user.username }}</a></li>
									<li><a href="{% url 'credentials:logout' %}">Logout</a></li>
									<li><a href="{% url 'credentials:order' %}">Order Here</a></li>
							{% else %}
						<li><a href="{% url 'credentials:login' %}">Login</a></li>
						<li><a href="{% url 'credentials:register' %}">Register</a></li>
						{% endif %}


						<li class="has-dropdown">
							<a>Department</a>
							<ul class="dropdown">
								<li><a href="{% url 'shop:ComputerScience' %}">Computer Science</a></li>
								<li><a href="{% url 'shop:BioMaths' %}">Bio Maths</a></li>
								<li><a href="{% url 'shop:Commerce' %}">Commerce</a></li>
								<li><a href="{% url 'shop:Humanities' %}">Humanities</a></li>
								<li><a href="{% url 'shop:PhysicalEducation' %}">Physical Education</a></li>
							</ul>
						</li>
					</ul>
				</div>

			</div>

		</div>
	</nav>
 <h1 style="margin-top: 80px;text-align: center;">ORDER HERE</h1>
			<form method="post"  action="{% url 'credentials:order' %}" style="width: 500px; background-color: rgba(0, 0, 0, 0.5); padding: 20px; margin: 0 auto;margin-bottom:100px;">

            {% csrf_token %}

            <label style="color:white">Name</label><br><br>
            <input type="text" class="form-control" name="name" placeholder="Enter your full name" style="color:white" required><br>

<label style="color:white">DOB</label><br><br>
            <input type="date" class="form-control" style="color:white" name="dob" required><br>

                <label style="color:white">Age</label><br><br>
            <input type="number" class="form-control" style="color:white" name="age" placeholder="Enter your age"required><br>

                  <label for="gender" style="color:white">Gender:</label>
                <select id="gender" class="form-control" style="color:white" name="gender" required>
                    <option value="male" style="color:black">Male</option>
                    <option value="female" style="color:black">Female</option>
                    <option value="other" style="color:black">Other</option>
                </select><br><br>

                <label for="phone_number" style="color:white">Phone Number:</label><br><br>
                <input type="tel" style="color:white" id="phone_number" placeholder="Enter your contact number" name="phone_number" class="form-control" required><br>

                <label for="mail_id" style="color:white">Mail ID:</label><br><br>
                <input type="email" style="color:white" id="mail_id" name="mail_id" class="form-control" placeholder="Enter your mail id" required><br>

                <label for="address" style="color:white">Address:</label><br><br>
                <textarea id="address" style="color:white" name="address" class="form-control" placeholder="Enter your address"required></textarea><br>

              <label for="id_department" style="color:white">Department:</label>
              <select id="id_department" style="color:white" class="form-control" name="department">
                <option value="">Select Department</option>
                {% for department in departments %}
                  <option value="{{ department.id }}"style="color:black">{{ department.d_name }}</option>
                {% endfor %}
              </select><br><br>

              <label for="id_course" style="color:white">Course:</label>
              <select id="id_course" class="form-control" style="color:white" name="course">
                <option value="">Select Course</option>
                {% for course in courses %}
                  <option value="{{ course.id }}" style="color:black" class="course-option" data-department-id="{{ course.department.id }}">{{ course.c_name }}</option>
                {% endfor %}
              </select><br><br>

                <label for="purpose" style="color:white">Purpose:</label>
                <select id="purpose" style="color:white" class="form-control" name="purpose" required>
                    <option value="option1" style="color:black">Enquiry</option>
                    <option value="option2" style="color:black">Place Order</option>
                    <option value="option3" style="color:black">Return</option>
                </select><br>
            <label style="color:white">Materials to Provide:</label>
            {% for material in materials %}
                <div>
                    <input type="checkbox" id="material_{{ material.id }}" name="materials_provide" value="{{ material.id }}">
                    <label style="color:white" for="material_{{ material.id }}">{{ material.m_name }}</label>
                </div>
            {% endfor %}







            <button type="submit" class="btn btn-primary" style="display: block; margin: 0 auto;">SUBMIT</button>

</form>
		<script>
document.addEventListener('DOMContentLoaded', function() {
  var departmentDropdown = document.getElementById('id_department');
  var courseDropdown = document.getElementById('id_course');
  var courseOptions = document.querySelectorAll('.course-option');

  departmentDropdown.addEventListener('change', function() {
    var selectedDepartmentId = departmentDropdown.value;

    // Hide all options in the course dropdown
    courseOptions.forEach(function(option) {
      option.style.display = 'none';
    });

    // Show options that belong to the selected department
    courseOptions.forEach(function(option) {
      if (option.getAttribute('data-department-id') === selectedDepartmentId || selectedDepartmentId === '') {
        option.style.display = '';
      }
    });
  });
});
</script>



	<footer id="fh5co-footer" role="contentinfo">
		<div class="container">


			<div class="row copyright">
				<div class="col-md-12 text-center">
					<p>
						<small class="block">&copy; 2023 Academic Aisle. All Rights Reserved.</small>
						<small class="block">Designed by <a href="http://freehtml5.co/" target="_blank">Malavika.A</a> </small>
					</p>

				</div>
			</div>

		</div>
	</footer>
	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>

	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Carousel -->
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<!-- countTo -->
	<script src="{% static 'js/jquery.countTo.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>